---
title: 'MAT221E: Probability Theory'
site: distill::distill_website
---

## Instructor Information

**Instructor:** Gül İnan

**E-mail:** inan@itu.edu.tr

**Office:** Room 424 @ Department of Mathematics 

**Office hour:** You can ask me your questions right after the class, or 
send me an e-mail for your queries and/or for scheduling
an online appointment via Zoom.

## Course Information  

**Course Type:** Must course for undergraduate students.

**Course Credits:** 3 local credits.

**Course Prerequisites:** None.

**Course Description:** This course is an introductory level probability class on introducing following concepts: sample space, probability measure on a sigma-algebra, Kolmogorov axioms, conditional probability, combinatorial methods, Bayes theorem. Random variables, discrete density functions, continuous density functions, functions of random variables, bivariate joint density functions, marginal and conditional density functions, independent random variables. Definition and properties of expectations. Chebyshev inequality. Moment generating functions. Special discrete and continuous distributions. Limit theorems, law of large numbers, central limit theorem. Slutsky's theorem. 

**Class Schedule:** Thursdays between 11:30-14:30 p.m.

**Classroom:** Room D201 @ Faculty of Arts and Sciences.

**Covid-19 update:** Wearing mask is required in shared spaces for all individuals, including those who are fully vaccinated. For a full list of regulations, please follow ITU main page. 

**Course Objectives:** This course aims to: 

1.	To provide the basic concepts of probability.
2.	To set up probability models for a range of random phenomena, both discrete and continuous.
3.	To develop critical thinking skills and abilities to apply calculus techniques (i.e., limits,
derivatives, integration, infinite series) to assess the probability of an event.

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">

**Course Tentative Plan**: We will closely follow the weekly schedule given below.
However, weekly class schedules are subject to change depending on the progress we make as a class.

| **Week**  | **Topic**                           |  History| Python/Colab | <br>Additional Documents|
| :-----:   |:------------------------------------|:------------------|:------:|:-------:|
| 1         | Random experiments, sample spaces, and events, and set operations. Counting methods, combinatorial methods, product rule, permutation, combination, binomial expansion, multinomial expansion, tree diagram.| | | |
| 2         | Algebra of events, sigma-algebra of events, Borel sets, probability measure on a sigma-algebra. Kolmogorov axioms and related corollaries (with proofs).| [Andrey Kolmogorov](https://en.wikipedia.org/wiki/Andrey_Kolmogorov) | | |
| 3         | Conditional probability, multiplication rule, independence of events, extension to multiple events.| | | |
| 4         | Bayes' theorem and the law of total probability.| [Thomas Bayes](https://en.wikipedia.org/wiki/Thomas_Bayes) | |[Bayes' Theorem and Covid-19 testing](https://www.theguardian.com/world/2021/apr/18/obscure-maths-bayes-theorem-reliability-covid-lateral-flow-tests-probability) | 
| 5         | Random variables, distributions and probability mass functions, cumulative distribution function. | |[🔗](https://colab.research.google.com/drive/1G4hPDOpq_9YRMIyST8sr_UMBLF6ythhC?usp=sharing)  | |
| 6 | Definition of Expectation, Special expectations: mean and variance. Special discrete distributions: Bernoulli, and Binomial distributions.  | [Jacob (James) Bernoulli](https://en.wikipedia.org/wiki/Jacob_Bernoulli) |  [🔗](https://colab.research.google.com/drive/1nDe0O7LgRs9OKHjESBWjzdeiVdxSMuED?usp=sharing)| |
| 7 | Special discrete distributions: Poisson, Geometric, Negative Binomial, Hypergeometric, and discrete uniform distributions. **Quiz I during lecture hour.** |[Siméon Denis Poisson](https://en.wikipedia.org/wiki/Sim%C3%A9on_Denis_Poisson)| [🔗](https://colab.research.google.com/drive/1PvczfQSX8_YuyLqjqIFrOg0b3yJtVErZ?usp=sharing) | [Quiz I](Quiz_I.pdf) | 
| 8 | ITU Fall Break.  | | |
| 9 | Continuous random variables: Probability density functions, cumulative distribution function, expectation, variance, percentiles, median.| | | [Histograms and Density Plots](https://towardsdatascience.com/histograms-and-density-plots-in-python-f6bda88f5ac0)|
| 10 | **Midterm on December 9, 2021 during lecture hour.** | | | |
| 11 | Special continuous distributions: Normal distribution, Normal approx. to Binomial, Gamma, Exponential, and Uniform distributions.| [Abraham de Moivre](https://en.wikipedia.org/wiki/Abraham_de_Moivre), [Carl Friedrich Gauss](https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss), [History of Random Numbers](https://tashian.com/articles/a-brief-history-of-random-numbers/)| [🔗](https://colab.research.google.com/drive/1cEV7oTgfNUfxtuJae7PYrb2TWtqGfDP4?usp=sharing)| [Random Number Generation](https://en.wikipedia.org/wiki/Random_number_generation)|
| 12 | Joint distributions: Joint and marginal distributions. Independent r.v.s. Multinomial distribution. | | | |
| 13 |Covariance and correlation. Conditional distributions. Conditional expectation. Conditional variance. Bivariate Normal distribution. | | | |
| 14 | Transformations: Change of variables, sum of two random variables, convolutions.| | | |
| 15 | Moments: Moment generating functions, summaries of a distribution, sample moments. | | | |
| 15 | Inequalities. Limit theorems: law of large numbers and central limit theorem. Chi-square dist.| | | |

**Suggested Video for Winter Break: The Galton Board**

<iframe width="500" height="352" src="https://www.youtube.com/embed/9QuPHf1xi-4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Student Learning Outcomes:** A student who completed this course successfully is expected to: 

1.	Understand and apply basic concepts of probability.
2.	Understand probability distributions for both discrete and continuous phenomena.
3.  Calculate basic characteristics such as mean and variance of probability distributions, and any probability
associated with this distributions.
4.	Use special probability distributions for modeling events.
5.	Use limit theorems.

immediately following the course, and/or a few months after the course.

**Textbook:**  All lecture materials. Lecture materials (notes, assignments, etc) will be uploaded on [Ninova](https://ninova.itu.edu.tr).

**Course Workload:** 2 __quizzes__, 1 midterm exam, and 1 final exam  (see the grading policy below). 

**Recommended Bibliography:** Students are encouraged to consult the following
sources on their own:

1. DeGroot., M.H. and Schervish, M.J. (2012). Probability and Statistics. Boston: Addison-Wesley, c2012.
[Hard copy available at ITU Mustafa Inan Library with CALL #QA273 .D445 2012].  (Available on Ninova)
2. Hogg, V.H. and Craig, A.T. (1995). Introduction to Mathematical Statistics. New Jersey: Prentice-Hall International.  [Hard copy available at ITU Mustafa Inan Library with CALL #QA276 .H643 1995].  (Available on Ninova)
3. Hogg, R. V., Tanis, E. A., and Zimmerman, D.L. (2010). Probability and Statistical Inference. Upper Saddle River, NJ, USA: Pearson/Prentice Hall. (Available on Ninova)
4. Miller, I. and Miller, M. (2004). John E. Freund's mathematical statistics with applications. Upper Saddle River, NJ. [Hard copy available at ITU Mustafa Inan Library Reserve with CALL #QA276 .M55 2004].  (More recent version is available on Ninova)

 
**Off-Campus Access to the ITU Library E-sources:**  

Access to library e-sources remotely
is possible with a library account. Users without a library account should apply for the library registration at https://kutuphane.itu.edu.tr/en/register. After setting the web configurations given at https://kutuphane.itu.edu.tr/en/servicesweb-browser-proxy-settings only once on your computer, you will able to have an access to ITU Library e-sources.


**Selected Important Dates:**
For the official ITU Fall 2021 academic calendar, please visit:

https://www.sis.itu.edu.tr/TR/ogrenci/akademik-takvim/akademik-takvimler/takvim2022/lisans-akademik-takvimi.php

Here are some selected important dates in Fall 2021 semester:

October 4, 2021: First day of classes.

October 4-8, 2021: Add-drop week.

October 29, 2021: Republic Day of Turkey (Friday, No classes).

November 22-26, 2021: ITU Fall Break (No classes).

January 1, 2022: New year (Saturday).

January 14, 2022: Last day of classes.

January 17-30, 2022: Final exam week.

I also honor other national and religious holidays. Students, who needs flexibility on individual-based studies overlapping with these special days, can inform me.


## Course Policies

Please read the information below as a reference for how this class will be conducted. 

**Grading Policy:**

- Assessment Method    \quad      \quad \quad                Total Contribution to Final Grade:
  - 2 quizzes each 10%,            
  - 1 midterm exam                           40%,
  - 1 final exam                                   40%.
   
- **Midterm date**: December 9, 2021 during the lecture hour in class. 
- **Student studies, namely, quizzes and exam papers which are not written well, does not follow a proper mathematical writing language, and are hard to review, will get "0" credit for that question.**
- Please see an example for **a good homework** on Ninova.
- Please read the general advice given at:

  http://ma117.math.metu.edu.tr/course-info/general-advice/.

**Late Submission Policy:** There are **NO** make-ups for missed quizzes.

**Final Exam Attendance Policy:** At least 20% of in-semester studies.

**Make-Up Exam Policy:** The students who miss either midterm exam or final exam due to a health problem
can take a make-up exam as long as they have a valid medical report taken on the exam day. The medical report should be handed in immediately (within two days of its expiration). 


**Class Attendance Policy:** 

The students must attend at least 70% of classes and
are deemed responsible to manage his/her absences.

**Participation Policy:** 

The students are expected to ask and answer
questions, participate in in-class activities, and
show their interest and engagement in the class. 


**E-mail Policy:**

Please:

1. Use a proper descriptive subject line (which may consist of the course number MAT221E followed
by a short phrase summarizing the subject of your e-mail).
2. Start off your e-mail with a proper greeting, introduce yourself (give your name), then state your problem as short as possible.
3. Finally, use a proper closing and then finish your e-mail with your first name and so on.

Feel free to send me e-mails. But be sure you that give me enough time to get back to you. In the past, I have had pretty much tolerance for e-mail messages sent after business hours and at weekends. But, now, due to pandemic, I should say that I may not appreciate these e-mails anymore.
Lastly, e-mails asking for grade grubbing at the end of the semester are not welcomed.


**Academic Honesty Policy:** 

At every stage of the academic life, every ITU student is responsible for obeying the academic honesty policy of ITU stated below:

https://odek.itu.edu.tr/en/code-of-honor/ethics-in-university-life.
   

**Equity, Diversity, and Inclusion:** 

In this class, I am committed to cultural and individual differences and diversity as including, but not limited to, age, disability, ethnicity, gender, gender identity, language, national origin, race, religion, culture, and socioeconomic status and I acknowledge the value of differences. 

  
**Student with Special Needs:** 

If you are a student with special needs, let me know
that how we can adjust the course environment and materials in accordance with your needs. 
Furthermore, you are also invited to contact the office of students with special needs at:

http://engelsiz.itu.edu.tr/.

**ITU Distance Education Policy:** 

Sharing the lecture recordings or its piece with third parties is strictly forbidden. Furthermore, the recordings are subject to investigation by the authorities as needed. For that reason, be sure that you behave (both orally and verbally) responsibly in this virtual class. Please visit:

https://online.itu.edu.tr/,

for more information on distance education regulations at ITU.